kind: pipeline
name: docker-build
type: docker

steps:
  - name: build
    image: loongcr.lcpu.dev/lcpu/archlinux:base
    volumes:
    - name: dockersock
      path: /var/run/user/1001/docker.sock
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_HOST: unix:///run/user/1001/docker.sock
    commands:
    - pacman -Sy --noconfirm && pacman -S --noconfirm docker go
    - CGO_ENABLED=0 GOOS=linux GOARCH=loong64 go build -a -tags netgo -o release/linux/loong64/drone-s3
    - docker build -t loongcr.lcpu.dev/drone/s3:latest -f ./docker/Dockerfile.linux.loong64 .
    - docker login -u="\$app" -p="$DOCKER_PASSWORD" loongcr.lcpu.dev
    - docker push loongcr.lcpu.dev/drone/s3:latest
node:
  size: small
volumes:
- name: dockersock
  host:
    path: /var/run/user/1001/docker.sock
